'use client';
import { useEffect, useState } from 'react';
import RoleSelect from '../RoleSelect';
import { api, inp, Field, Toggle, Num, Btn, useNotice } from '../store/ui';
const QT: any = { short: 'نص قصير', long: 'نص طويل', number: 'رقم', select: 'قائمة اختيار' }; const ST: any = { pending: '⏳ قيد المراجعة', accepted: '✅ مقبول', rejected: '❌ مرفوض' };
const blank = () => ({ name: '', description: '', buttonLabel: 'قدّم الآن', questions: [{ label: '', type: 'short', required: true, options: [] }] as any[], roleId: null as string | null, minVotes: 3, cooldownDays: 7, active: true, sortOrder: 0 });
export default function ApplicationsManager({ guildId }: { guildId: string }) {
  const base = `/api/guilds/${guildId}/staff`; const [forms, setForms] = useState<any[]>([]); const [apps, setApps] = useState<any[]>([]); const [ed, setEd] = useState<any>(null); const [pub, setPub] = useState(false); const nt = useNotice();
  const load = () => { api(`${base}/forms`).then((j) => setForms(j.forms)).catch(nt.err); api(`${base}/applications`).then((j) => setApps(j.applications)).catch(nt.err); }; useEffect(() => { load(); }, []);
  const up = (k: string, v: any) => setEd((e: any) => ({ ...e, [k]: v })); const setQ = (i: number, p: any) => up('questions', ed.questions.map((q: any, j: number) => (j === i ? { ...q, ...p } : q)));
  async function save() { try { const { guildId: _g, createdAt, ...b } = ed; await api(`${base}/forms`, 'POST', b); nt.ok('تم الحفظ'); setEd(null); load(); } catch (e) { nt.err(e); } }
  async function del(f: any) { if (confirm(`حذف «${f.name}»؟`)) { try { await api(`${base}/forms?id=${f.id}`, 'DELETE'); load(); } catch (e) { nt.err(e); } } }
  async function publish() { setPub(true); try { const s = await api(`${base}/settings`); if (!s.applications.channelId) throw new Error('اختر قناة لوحة التقديم من تبويب الإعدادات أولاً'); await api(`/api/guilds/${guildId}/general/publish`, 'POST', { module: 'staff', panel: 'apply', channelId: s.applications.channelId }); nt.ok('تم إرسال طلب النشر'); } catch (e) { nt.err(e); } finally { setPub(false); } }
  if (ed) return <div className="space-y-3 max-w-2xl"><div className="flex justify-between"><h2 className="font-bold text-lg">{ed.id ? 'تعديل استمارة' : 'استمارة جديدة'}</h2><Btn kind="ghost" onClick={() => setEd(null)}>رجوع</Btn></div>
    <section className="bg-white border rounded-lg p-4 grid md:grid-cols-2 gap-3"><Field label="اسم الاستمارة"><input className={inp} maxLength={60} value={ed.name} onChange={(e) => up('name', e.target.value)} /></Field><Field label="نص زر التقديم"><input className={inp} maxLength={80} value={ed.buttonLabel} onChange={(e) => up('buttonLabel', e.target.value)} /></Field>
      <div className="md:col-span-2"><Field label="الوصف"><textarea className={inp} rows={2} maxLength={500} value={ed.description} onChange={(e) => up('description', e.target.value)} /></Field></div>
      <Field label="الرتبة الممنوحة عند القبول"><RoleSelect guildId={guildId} value={ed.roleId ? [ed.roleId] : []} onChange={(v) => up('roleId', v[v.length - 1] || null)} /></Field>
      <Field label="الحد الأدنى للأصوات قبل القرار"><Num min={0} value={ed.minVotes} onChange={(v: number) => up('minVotes', v)} /></Field><Field label="فترة الانتظار بعد الرفض (يوم)"><Num min={0} value={ed.cooldownDays} onChange={(v: number) => up('cooldownDays', v)} /></Field><Field label="الترتيب"><Num min={0} value={ed.sortOrder} onChange={(v: number) => up('sortOrder', v)} /></Field><Toggle label="مفتوحة للتقديم" value={ed.active} onChange={(v) => up('active', v)} /></section>
    <section className="bg-white border rounded-lg p-4 space-y-2"><div className="flex justify-between"><h3 className="font-bold">الأسئلة (حتى 25؛ تُعرض 5 في كل نافذة)</h3>{ed.questions.length < 25 && <Btn kind="ghost" onClick={() => up('questions', [...ed.questions, { label: '', type: 'short', required: true, options: [] }])}>+ سؤال</Btn>}</div>
      {ed.questions.map((q: any, i: number) => <div key={i} className="grid md:grid-cols-4 gap-2 items-end border rounded p-2 bg-sand/40"><div className="md:col-span-2"><Field label={`السؤال ${i + 1}`}><input className={inp} maxLength={45} value={q.label} onChange={(e) => setQ(i, { label: e.target.value })} /></Field></div>
        <Field label="النوع"><select className={inp} value={q.type} onChange={(e) => setQ(i, { type: e.target.value })}>{Object.entries(QT).map(([k, v]) => <option key={k} value={k}>{v as string}</option>)}</select></Field>
        <div className="flex gap-2 items-center"><Toggle label="إجباري" value={q.required} onChange={(v) => setQ(i, { required: v })} /><Btn kind="danger" onClick={() => up('questions', ed.questions.filter((_: any, j: number) => j !== i))}>حذف</Btn></div>
        {q.type === 'select' && <div className="md:col-span-4"><Field label="الخيارات (سطر لكل خيار)"><textarea className={inp} rows={2} value={q.options.join('\n')} onChange={(e) => setQ(i, { options: e.target.value.split('\n').map((x) => x.trim()).filter(Boolean) })} /></Field></div>}</div>)}</section>
    {nt.view}<Btn onClick={save}>حفظ</Btn></div>;
  return <div className="space-y-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="text-lg font-bold">استمارات التقديم</h2><div className="flex gap-2"><Btn kind="ghost" disabled={pub} onClick={publish}>نشر / تحديث لوحة التقديم</Btn><Btn onClick={() => { nt.clear(); setEd(blank()); }}>+ استمارة</Btn></div></div>{nt.view}
    <div className="grid md:grid-cols-2 gap-3">{forms.map((f) => <div key={f.id} className={`bg-white border rounded-lg p-3 space-y-1 ${f.active ? '' : 'opacity-60'}`}><b>{f.name}</b><p className="text-xs text-gray-600">{(f.questions || []).length} سؤال · حد الأصوات {f.minVotes} · انتظار {f.cooldownDays} يوم</p><div className="flex gap-2"><Btn kind="ghost" onClick={() => { nt.clear(); setEd({ ...f }); }}>تعديل</Btn><Btn kind="danger" onClick={() => del(f)}>حذف</Btn></div></div>)}{!forms.length && <p className="text-gray-500">لا توجد استمارات.</p>}</div>
    <h3 className="font-bold">آخر الطلبات</h3><div className="bg-white border rounded-lg overflow-x-auto"><table className="w-full text-sm"><thead className="bg-sand text-right"><tr>{['المتقدّم', 'الاستمارة', 'الحالة', 'الأصوات', 'التاريخ'].map((h) => <th key={h} className="p-2">{h}</th>)}</tr></thead>
      <tbody>{apps.map((a) => <tr key={a.id} className="border-t"><td className="p-2 font-mono text-xs" dir="ltr">{a.userId}</td><td className="p-2">{a.form}</td><td className="p-2">{ST[a.status]}{a.reviewReason && <span className="text-xs text-gray-500"> — {a.reviewReason}</span>}</td><td className="p-2">👍 {a.up} · 👎 {a.down} · ➖ {a.neutral}</td><td className="p-2 text-xs">{new Date(a.createdAt).toLocaleString('ar-EG')}</td></tr>)}{!apps.length && <tr><td colSpan={5} className="p-4 text-center text-gray-500">لا توجد طلبات</td></tr>}</tbody></table></div></div>;
}
