import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { guildRoute, bumpConfig, audit } from '@/lib/api';
const snow = z.string().regex(/^\d{5,25}$/); const sched = z.object({ enabled: z.boolean(), day: z.number().int().min(0).max(31), hour: z.number().int().min(0).max(23) });
const schema = z.object({ reportChannelId: snow.nullable(), supportChannelIds: z.array(snow).max(30), weekly: sched.refine((s) => s.day <= 6, { message: 'يوم الأسبوع من 0 إلى 6' }), monthly: sched.refine((s) => s.day >= 1 && s.day <= 28, { message: 'يوم الشهر من 1 إلى 28' }),
  inactivity: z.object({ enabled: z.boolean(), days: z.number().int().min(1).max(365) }), applications: z.object({ channelId: snow.nullable(), reviewChannelId: snow.nullable(), title: z.string().max(256), description: z.string().max(2000), color: z.string().regex(/^#[0-9a-fA-F]{6}$/) }) });
const DEFAULTS = { reportChannelId: null, supportChannelIds: [], weekly: { enabled: true, day: 6, hour: 9 }, monthly: { enabled: true, day: 1, hour: 9 }, inactivity: { enabled: false, days: 7 }, applications: { channelId: null, reviewChannelId: null, title: '', description: '', color: '#5865f2' } };
export const GET = guildRoute(null, async ({ guildId }) => { const g: any = await prisma.guild.upsert({ where: { id: guildId }, create: { id: guildId }, update: {} }); const s = g.settings?.staff || {}; return { ...DEFAULTS, ...s, weekly: { ...DEFAULTS.weekly, ...(s.weekly || {}) }, monthly: { ...DEFAULTS.monthly, ...(s.monthly || {}) }, inactivity: { ...DEFAULTS.inactivity, ...(s.inactivity || {}) }, applications: { ...DEFAULTS.applications, ...(s.applications || {}) }, timezone: g.settings?.timezone || 'Africa/Cairo' }; });
export const PUT = guildRoute(schema, async ({ guildId, uid, body }) => { const g: any = await prisma.guild.upsert({ where: { id: guildId }, create: { id: guildId }, update: {} }); await prisma.guild.update({ where: { id: guildId }, data: { settings: { ...(g.settings || {}), staff: body } } }); await bumpConfig(guildId); await audit(guildId, uid, 'staff.settings.update', {}); return { ok: true }; });
