'use client';
import { useEffect, useState } from 'react';
import { api, inp, Field, Btn, useNotice } from '../store/ui';
const dur = (s: number) => { const d = Math.floor(s / 86400), h = Math.floor((s % 86400) / 3600), m = Math.floor((s % 3600) / 60); return `${d ? d + ' ي ' : ''}${h} س ${m} د`; };
export default function AdminPanel() {
  const [d, setD] = useState<any>(null); const [f, setF] = useState({ kind: 'guild', targetId: '', reason: '' }); const nt = useNotice(); const [q, setQ] = useState('');
  const load = () => api('/api/admin/status').then(setD).catch(nt.err); useEffect(() => { load(); const t = setInterval(load, 15000); return () => clearInterval(t); }, []);
  async function run(fn: () => Promise<any>, ok: string) { try { await fn(); nt.ok(ok); load(); } catch (e) { nt.err(e); } }
  if (!d) return <>{nt.view || <p>...</p>}</>; const b = d.bot; const list = d.guilds.filter((g: any) => !q || g.name?.includes(q) || g.id.includes(q));
  return <div className="space-y-5">{nt.view}
    <section className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['حالة البوت', b ? (b.online ? '🟢 متصل' : '🔴 غير متصل') : '⚪ لا توجد بيانات'], ['مدة التشغيل', b ? dur(b.uptimeSec) : '—'], ['Ping', b ? `${b.ping} ms` : '—'], ['السيرفرات', b?.guilds ?? '—'], ['الذاكرة', b ? `${b.memoryMb} MB` : '—']].map(([l, v]) => <div key={l as string} className="bg-white border rounded-lg p-3 text-center"><div className="font-bold">{v}</div><div className="text-xs text-gray-500">{l}</div></div>)}</section>
    {b && !b.online && <p className="bg-red-50 text-red-700 rounded p-3 text-sm">آخر نبضة منذ {Math.round((b.lastBeatMs || 0) / 1000)} ثانية. تحقق من تشغيل البوت (راجع جدول استكشاف الأخطاء).</p>}
    <section className="bg-white border rounded-lg p-4 flex flex-wrap items-center justify-between gap-3"><div><b>وضع الصيانة</b><p className="text-sm text-gray-600">عند التفعيل يتوقف البوت عن الرد على الأزرار والقوائم لجميع الأعضاء (المالك مستثنى).</p></div>
      <Btn kind={d.maintenance ? 'danger' : 'primary'} onClick={() => run(() => api('/api/admin/maintenance', 'POST', { enabled: !d.maintenance }), d.maintenance ? 'تم إيقاف الصيانة' : 'تم تفعيل الصيانة')}>{d.maintenance ? '🔴 إيقاف الصيانة' : '🛠️ تفعيل الصيانة'}</Btn></section>
    <section className="bg-white border rounded-lg p-4 space-y-3"><h3 className="font-bold">🚫 القائمة السوداء</h3>
      <div className="grid md:grid-cols-4 gap-2 items-end"><Field label="النوع"><select className={inp} value={f.kind} onChange={(e) => setF({ ...f, kind: e.target.value })}><option value="guild">سيرفر (يغادره البوت)</option><option value="user">مستخدم</option></select></Field>
        <Field label="المعرّف (ID)"><input dir="ltr" className={inp} value={f.targetId} onChange={(e) => setF({ ...f, targetId: e.target.value.trim() })} /></Field><Field label="السبب"><input className={inp} maxLength={200} value={f.reason} onChange={(e) => setF({ ...f, reason: e.target.value })} /></Field>
        <Btn disabled={!f.targetId} onClick={() => run(async () => { await api('/api/admin/blacklist', 'POST', f); setF({ ...f, targetId: '', reason: '' }); }, 'تمت الإضافة')}>إضافة</Btn></div>
      <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-sand text-right"><tr>{['النوع', 'المعرّف', 'السبب', 'التاريخ', ''].map((h) => <th key={h} className="p-2">{h}</th>)}</tr></thead>
        <tbody>{d.blacklist.map((x: any) => <tr key={x.id} className="border-t"><td className="p-2">{x.kind === 'guild' ? 'سيرفر' : 'مستخدم'}</td><td className="p-2 font-mono text-xs" dir="ltr">{x.targetId}</td><td className="p-2">{x.reason || '—'}</td><td className="p-2 text-xs">{new Date(x.createdAt).toLocaleDateString('ar-EG')}</td>
          <td className="p-2"><Btn kind="ghost" onClick={() => run(() => api(`/api/admin/blacklist?kind=${x.kind}&targetId=${x.targetId}`, 'DELETE'), 'تمت الإزالة')}>إزالة</Btn></td></tr>)}{!d.blacklist.length && <tr><td colSpan={5} className="p-3 text-center text-gray-500">القائمة فارغة</td></tr>}</tbody></table></div></section>
    <section className="bg-white border rounded-lg p-4 space-y-3"><div className="flex justify-between items-center"><h3 className="font-bold">🌐 السيرفرات ({d.guilds.length})</h3><input className="border rounded p-1 text-sm" placeholder="بحث بالاسم أو ID" value={q} onChange={(e) => setQ(e.target.value)} /></div>
      <div className="overflow-x-auto max-h-[28rem]"><table className="w-full text-sm"><thead className="bg-sand text-right sticky top-0"><tr>{['السيرفر', 'الأعضاء', 'المالك', 'انضم البوت', ''].map((h) => <th key={h} className="p-2">{h}</th>)}</tr></thead>
        <tbody>{list.map((g: any) => <tr key={g.id} className="border-t"><td className="p-2"><b>{g.name}</b><div className="font-mono text-xs text-gray-400" dir="ltr">{g.id}</div></td><td className="p-2">{g.memberCount}</td><td className="p-2 font-mono text-xs" dir="ltr">{g.ownerId}</td><td className="p-2 text-xs">{g.joinedAt ? new Date(g.joinedAt).toLocaleDateString('ar-EG') : '—'}</td>
          <td className="p-2 flex gap-1"><a className="border rounded px-2 py-1 text-xs bg-white" href={`/${g.id}`}>فتح اللوحة</a><Btn kind="ghost" onClick={() => confirm(`مغادرة «${g.name}»؟`) && run(() => api('/api/admin/guilds', 'POST', { action: 'leave', guildId: g.id }), 'تم طلب المغادرة')}>مغادرة</Btn><Btn kind="danger" onClick={() => confirm(`حظر «${g.name}» ومغادرته؟`) && run(() => api('/api/admin/blacklist', 'POST', { kind: 'guild', targetId: g.id, reason: 'حظر من لوحة المالك' }), 'تم الحظر')}>حظر</Btn></td></tr>)}</tbody></table></div></section></div>;
}
